
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = 'v0.1-5-g510a2fe'
version_full = '510a2feed6ade8810897a16b92a6d2281e331d2d'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

